### ISSUE TITLE
For glove embeddings and inference step

### ISSUE THREAD

**Issue by jingunkwon** [X-AISIG/LenAtten#2]
Hello!

I have a couple of questions for your implementation to reproduce the reported scores in acl findings.

By carefully reading your codes, I think I want to get the following preprocessed files. 

"path = f'/home/fltsm/word-embedding/special.tokens.{dim}d.pkl'"
  self.vectors_list_path = f'{path}/out.6B.{dim}.dat'
  self.words_list_path = f'{path}/out.6B.{dim}_words.pkl'
  self.ids_list_path = f'{path}/out.6B.{dim}_idx.pkl'
  
For the inference step, how did you give the desired length (remained-length)?
Did you give the gold target length for the inference step?

Thanks in advance!

**Comment by Alleinx** [comment]
Hi! Thank you for your interest in our work.

"For the inference step, how did you give the desired length (remained-length)?"
- For the **"Various Preset Lengths"** experiment (section 4.3), in each run, we set the desired length as a predefined number for all data points in the test set. (e.g. 30, 50, 75 characters respectively). This means that all generated summaries are expected to have (30, 50, 75, ...) characters.

- In the rest of the experiments, for each **(article, golden summary)** pair, we set the desired length as the length of the golden summary.

**Comment by jingunkwon** [comment]
Cool!

I completely understand! Thank you so much!
Can you share the files for the glove embeddings as well?

Really appreciate your kind reply!

**Comment by ecwu** [comment]
Hi! I will answer your questions on the GloVe Embeddings.

Loading the preprocessed files ([generate-glove-embedding.py L47-52](https://github.com/X-AISIG/LenAtten/blob/279341c1b97967b3dd1336e05176c9a99d21dd9b/LA_Atten/generate_glove_embedding.py#L47-L52)) is for speed consideration, and the files are converted using the original [GloVe 6B embeddings](https://nlp.stanford.edu/data/glove.6B.zip). And the preprocessing procedures are implemented in the same py file: [L54-64](https://github.com/X-AISIG/LenAtten/blob/279341c1b97967b3dd1336e05176c9a99d21dd9b/LA_Atten/generate_glove_embedding.py#L54-L64) is for the conversion. [L65, L71-84](https://github.com/X-AISIG/LenAtten/blob/279341c1b97967b3dd1336e05176c9a99d21dd9b/LA_Atten/generate_glove_embedding.py#L71-L84) will generate those preprocessed files.

So, you only need to prepare a copy of GloVe Embeddings and rerun the preprocessing again.
1. Download the GloVe Embeddings
2. Change the Embedding size (`emb_dim`) in `data_util/config.py`
3. Change the `path` (at [L34](https://github.com/X-AISIG/LenAtten/blob/279341c1b97967b3dd1336e05176c9a99d21dd9b/LA_Atten/generate_glove_embedding.py#L34)) to your embedding folder (also, unzip the GloVe 6B embeddings here, the embeddings should be named in the format of `glove.6B.{dim}d.txt`, `{dim}` will be replaced to `emb_dim` defined in step 2.)
4. Run the code.

Notice: 
The `special.tokens.{dim}d.pkl` file declared at [L19](https://github.com/X-AISIG/LenAtten/blob/279341c1b97967b3dd1336e05176c9a99d21dd9b/LA_Atten/generate_glove_embedding.py#L19) is for testing purposes, which is not been used during training. So you can ignore it.

**Comment by jingunkwon** [comment]
Perfect!!
I appreciate your kindness.
I close this issue since everything is solved.
